export type InvoiceWorkspaceTranslations = Record<
    | 'unsaved'
    | 'build_tab'
    | 'money_tab'
    | 'sharing_tab'
    | 'line_count'
    | 'line_count_one'
    | 'amount_due'
    | 'send_email'
    | 'send_requires_save'
    | 'balance'
    | 'outstanding'
    | 'document_facts'
    | 'sharing_facts'
    | 'customer'
    | 'issue_date'
    | 'due_date'
    | 'payment_term'
    | 'days'
    | 'reference'
    | 'language'
    | 'bank_account'
    | 'public_link'
    | 'email_delivery'
    | 'not_queued'
    | 'reminders'
    | 'reminder_count'
    | 'reminder_count_one'
    | 'open_sharing'
    | 'not_available',
    string
>;
